http:
  services:
    blazegraph:
      loadBalancer:
        servers:
          - url: http://blazegraph:8080
  routers:
    blazegraph:
      rule: Host(`blazegraph.islandora.io`)
      service: blazegraph
