[worker.containerd]
  enabled = false
[worker.oci]
  enabled = true
  gc = false
[registry."islandora.io"]
  insecure=false
  ca=["./certs/rootCA.pem"]
  [[registry."islandora.io".keypair]]
    key="./certs/privkey.pem"
    cert="./certs/cert.pem"
