---
# Common to all services
x-common: &common
  restart: unless-stopped
  tty: true # Required for non-root users with selinux enabled.
  security_opt:
    - label=type:container_runtime_t # Required for selinux to access the docker socket and bind mount files.
  networks:
    default:
networks:
  default:

volumes:
  acme-data: {}
  activemq-data: {}
  blazegraph-data: {}
  cantaloupe-data: {}
  drupal-private-files: {}
  drupal-public-files: {}
  drupal-solr-config: {}
  fcrepo-data: {}
  mariadb-data: {}
  solr-data: {}

secrets:
  # Certificates are only used for development environments.
  CERT_PUBLIC_KEY:
    file: ./certs/cert.pem
  CERT_PRIVATE_KEY:
    file: ./certs/privkey.pem
  CERT_AUTHORITY:
    file: ./certs/rootCA.pem
  UID:
    file: ./certs/UID
  # Production secrets:
  ACTIVEMQ_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  ACTIVEMQ_WEB_ADMIN_PASSWORD:
    file: "./secrets/ACTIVEMQ_WEB_ADMIN_PASSWORD"
  ALPACA_JMS_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  DB_ROOT_PASSWORD:
    file: "./secrets/DB_ROOT_PASSWORD"
  DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD"
  DRUPAL_DEFAULT_DB_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_DB_PASSWORD"
  DRUPAL_DEFAULT_SALT:
    file: "./secrets/DRUPAL_DEFAULT_SALT"
  FCREPO_DB_PASSWORD:
    file: "./secrets/FCREPO_DB_PASSWORD"
  JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  JWT_PRIVATE_KEY:
    file: "./secrets/JWT_PRIVATE_KEY"

services:
  activemq:
    <<: *common
    image: islandora/activemq:6.4.3
    secrets:
      - source: ACTIVEMQ_PASSWORD
      - source: ACTIVEMQ_WEB_ADMIN_PASSWORD
    volumes:
      - activemq-data:/opt/activemq/data:rw

  alpaca:
    <<: *common
    depends_on:
      activemq:
        condition: service_healthy
    image: islandora/alpaca:6.4.3
    secrets:
      - source: ALPACA_JMS_PASSWORD
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY

  blazegraph:
    <<: *common
    image: islandora/blazegraph:6.4.3
    volumes:
      - blazegraph-data:/data:rw

  cantaloupe:
    <<: *common
    image: islandora/cantaloupe:6.4.3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
    volumes:
      - cantaloupe-data:/data:rw

  crayfits:
    <<: *common
    image: islandora/crayfits:6.4.3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  drupal:
    <<: *common
    build:
      args:
        REPOSITORY: islandora
        TAG: 6.4.3
      context: ./drupal
      x-bake:
        cache-from:
          - type=registry,ref=islandora.io/isle-site-template:local
          - type=registry,ref=islandora.io/isle-site-template:latest
        cache-to:
          - type=inline
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      DEVELOPMENT_ENVIRONMENT: "false"
      DRUPAL_DEFAULT_BROKER_URL: tcp://activemq:61613
      DRUPAL_DEFAULT_CANTALOUPE_URL: http://islandora.io/cantaloupe/iiif/2
      DRUPAL_DEFAULT_CONFIGDIR: /var/www/drupal/config/sync
      DRUPAL_DEFAULT_FCREPO_HOST: fcrepo
      DRUPAL_DEFAULT_FCREPO_PORT: 8080
      DRUPAL_DEFAULT_FCREPO_URL: http://fcrepo.islandora.io/fcrepo/rest/
      DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
      DRUPAL_DEFAULT_NAME: Islandora Digital Collections
      DRUPAL_DEFAULT_PROFILE: minimal
      DRUPAL_DEFAULT_SITE_URL: http://islandora.io/
      DRUPAL_DEFAULT_SOLR_CORE: default
      DRUPAL_ENABLE_HTTPS: "false"
      DRUSH_OPTIONS_URI: http://islandora.io/
      NGINX_REAL_IP_RECURSIVE: "off"
      NGINX_SET_REAL_IP_FROM: 127.0.0.1/32
      NGINX_SET_REAL_IP_FROM2: 172.0.0.0/8
      NGINX_SET_REAL_IP_FROM3: 192.168.0.0/16
    healthcheck:
      start_period: 0s
      retries: 3
    image: islandora.io/isle-site-template:local
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: UID
      - source: DB_ROOT_PASSWORD
      - source: DRUPAL_DEFAULT_ACCOUNT_PASSWORD
      - source: DRUPAL_DEFAULT_DB_PASSWORD
      - source: DRUPAL_DEFAULT_SALT
      - source: JWT_PRIVATE_KEY
      - source: JWT_PUBLIC_KEY
    volumes:
      - read_only: false
        source: drupal-public-files
        target: /var/www/drupal/web/sites/default/files
        type: volume
      - read_only: false
        source: drupal-private-files
        target: /var/www/drupal/private
        type: volume
      - drupal-solr-config:/opt/solr/server/solr/default:z,rw

  fcrepo:
    <<: *common
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      FCREPO_ALLOW_EXTERNAL_DEFAULT: http://default/
      FCREPO_ALLOW_EXTERNAL_DRUPAL: http://islandora.io/
      FCREPO_PERSISTENCE_TYPE: mysql
    image: islandora/fcrepo6:6.4.3
    secrets:
      - source: DB_ROOT_PASSWORD
      - source: FCREPO_DB_PASSWORD
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY
    volumes:
      - fcrepo-data:/data:rw

  fits:
    <<: *common
    image: islandora/fits:6.4.3

  homarus:
    <<: *common
    image: islandora/homarus:6.4.3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  houdini:
    <<: *common
    image: islandora/houdini:6.4.3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  hypercube:
    <<: *common
    image: islandora/hypercube:6.4.3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  init:
    entrypoint: /scripts/init-entrypoint.sh
    image: islandora/base:6.4.3
    networks:
      default:
    profiles:
      - none
    restart: "no"
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - ./certs:/certs:rw
      - ./secrets:/secrets:rw
      - ./scripts:/scripts:ro
      - ./docker-compose.yml:/docker-compose.yml:ro
      - ./drupal:/drupal:rw
      - /var/run/docker.sock:/var/run/docker.sock:z

  mariadb:
    <<: *common
    image: islandora/mariadb:6.4.3
    secrets:
      - source: DB_ROOT_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql:rw

  mergepdf:
    <<: *common
    image: islandora/mergepdf:6.4.3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  milliner:
    <<: *common
    environment:
      MILLINER_FEDORA6: true
    image: islandora/milliner:6.4.3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  solr:
    <<: *common
    depends_on:
      drupal:
        condition: service_healthy
    image: islandora/solr:6.4.3
    volumes:
      - solr-data:/data:rw
      - read_only: false
        source: drupal-solr-config
        target: /opt/solr/server/solr/default
        type: volume
        volume:
          nocopy: true

  traefik:
    <<: *common
    command: >-
      --ping=true
      --log.level=INFO
      --entryPoints.http.address=:80
      --entryPoints.http.forwardedHeaders.trustedIPs=127.0.0.1/32,172.0.0.0/8,192.168.0.0/16
      --entryPoints.http.http.encodedCharacters.allowEncodedSlash=true
      --entryPoints.http.http.encodedCharacters.allowEncodedPercent=true
      --entryPoints.http.http.encodedCharacters.allowEncodedQuestionMark=true
      --entryPoints.http.http.encodedCharacters.allowEncodedHash=true
      --entryPoints.http.transport.respondingTimeouts.readTimeout=60
      --providers.file.directory=/etc/traefik/dynamic
      --providers.docker=true
      --providers.docker.network=default
      --providers.docker.exposedByDefault=false
      --api.insecure=false
      --api.dashboard=false
      --api.debug=false
    depends_on:
      drupal:
        condition: service_healthy
    environment:
      DEVELOPMENT_ENVIRONMENT: "false"
      DOMAIN: islandora.io
      TLS_PROVIDER: self-managed
      URI_SCHEME: http
    healthcheck:
      start_period: 10s
      test: traefik healthcheck --ping
    image: traefik:v3.6.13@sha256:5e113a222e0a43c112bd8caeb0dfb42685be2c2eb190c79176c99c1259e4fa10
    networks:
      default:
        aliases:
          - activemq.islandora.io
          - blazegraph.islandora.io
          - fcrepo.islandora.io
          - islandora.io
          - solr.islandora.io
    ports:
      - "80:80"
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_PRIVATE_KEY
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/traefik:/etc/traefik/dynamic:ro
      - acme-data:/acme:rw
